{% set name = "yamlordereddictloader" %}
{% set version = "0.4.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 36af2f6210fcff5da4fc4c12e1d815f973dceb41044e795e1f06115d634bca13

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv "

requirements:
  host:
    - pip
    - python
  run:
    - python
    - pyyaml

test:
  imports:
    - yamlordereddictloader

about:
  home: https://github.com/fmenabe/python-yamlordereddictloader
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: YAML loader and dump for PyYAML allowing to keep keys order.

extra:
  recipe-maintainers:
    - PertuyF
    - bgruening
